Renamed RESET to ENCODER_RESET > name collision
A declaration of the GCONF_PARAMETER "RESET = 0x80" collides with a declaration name "RESET" which is necessary for the STM32F1 series. So I renamed the declaration to ENCODER_RESET, then I can compile for STM32F1.
In file included from C:\Users\mike\Documents\Arduino\BluePill_F103C8_20x4LCD_with_RGB_encoder\BluePill_F103C8_20x4LCD_with_RGB_encoder.ino:3:0:

C:\Users\mike\Documents\Arduino\libraries\ArduinoDuPPaLib-master\src/i2cEncoderLibV2.h:86:12: error: redeclaration of 'RESET'

   RESET =  0x80,

            ^~~~

In file included from C:\Users\mike\AppData\Local\Arduino15\packages\STM32\hardware\stm32\1.5.0\cores\arduino/stm32/stm32_def.h:10:0,

                 from C:\Users\mike\AppData\Local\Arduino15\packages\STM32\hardware\stm32\1.5.0\cores\arduino/stm32/clock.h:43,

                 from C:\Users\mike\AppData\Local\Arduino15\packages\STM32\hardware\stm32\1.5.0\cores\arduino/wiring_time.h:23,

                 from C:\Users\mike\AppData\Local\Arduino15\packages\STM32\hardware\stm32\1.5.0\cores\arduino/wiring.h:38,

                 from C:\Users\mike\AppData\Local\Arduino15\packages\STM32\hardware\stm32\1.5.0\cores\arduino/Arduino.h:32,

                 from sketch\BluePill_F103C8_20x4LCD_with_RGB_encoder.ino.cpp:1:

C:\Users\mike\AppData\Local\Arduino15\packages\STM32\hardware\stm32\1.5.0\system/Drivers/CMSIS/Device/ST/STM32F1xx/Include/stm32f1xx.h:171:3: note: previous declaration 'FlagStatus RESET'

   RESET = 0,

   ^~~~~

exit status 1
Error compiling for board Generic STM32F1 series.